// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:3ffae8be-e436-48d3-89bc-bd341ed95673",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_jF3cTED15",
    "aws_user_pools_web_client_id": "4jq5m1asevmeb0uaurqt4lf5v3",
    "oauth": {}
};


export default awsmobile;
